### ISSUE TITLE
Question about function classify_counts() in horsefuzz

### ISSUE THREAD

**Issue by EvanXiaa** [MelbourneFuzzingHub/aflteam#1]
Hi author, I wonder why you disable the optimization classify_counts() in horsefuzz. Could you please provide an example with more details? It seems that the the function has_new_bits() will also be misled to some extent. 
Thank you for replying!

**Comment by thuanpv** [comment]
Hi @Anderson-Xia. We do not call the classify_counts function because it could rearrange/update the bits in the coverage bitmaps while our task-aware fuzzing algorithm needs a consistent bitmap indexes. We also update the has_new_bits functions so that it can be "task-aware". That is, we apply a "mask" on the collected coverage bitmap to focus on the given tasks, i.e. functions. Please watch my talk https://www.youtube.com/watch?v=XaJVppiSFOM and/or read our ASE'21 NIER paper for more information. I hope it helps. Thuan

**Comment by EvanXiaa** [comment]
Thanks! 
I have read your paper before. I think the workflow is 

i. func_id[] records the relations between edges and functions(cksum)
ii. in apply_mask you check all covered edges and see if they correspond to target functions.
iii. for those functions not targeted, you set the location in coverage bitmap to 0.

Since the task-aware algorithm focuses on if an edge _i_ is covered(trace_bits[_i_] = 0 or not ), while the classify_counts only adjust the exact number of trace_bits[_i_] which stands for the execution num of an edge _i_, I wonder how classify_counts disturbed the map between edges and functions. 

Looking forward to your replying!

**Comment by thuanpv** [comment]
Thanks! I think you are right. We mainly did that because of this comment in the classify_counts function: https://github.com/MelbourneFuzzingHub/horsefuzz/blob/master/afl-fuzz.c#L1277. Perhaps we were too conservative ;)
